version: '3.8'

services:
  postgres:
    container_name: forum-pg
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: forum
    volumes:
      - pg_data:/var/lib/postgresql/data

  # api:
  #   build:
  #     context: .
  #   container_name: forum-api
  #   ports:
  #     - 3333:3333
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
volumes:
  pg_data:
