name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.5.0
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: .
