name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate prisma client
        run: pnpm prisma generate

      - name: Run unit tests
        run: pnpm test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push action
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            imanogui/forum-api:${{ steps.generate_tag.outputs.sha }}
            imanogui/forum-api:latest
          secrets: |
            PORT=${{ secrets.PORT }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }}
            JWT_PUBLIC_KEY=${{ secrets.JWT_PUBLIC_KEY }}
            CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
